# General Jekyll Config
highlighter: rouge
url: https://mediclassics-app.github.io
lsi: false
exclude: [ .gitignore, Gemfile, Gemfile.lock, LICENSE, README.md, jekyll.serve, jekyll.build ]

# Site Settings
baseurl:            "/bookshelf" # Base URL must end WITHOUT a slash, default: ""
timezone:           Asia/Seoul # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Build settings
host: localhost
port: 8384

destination: "docs"

# ref : https://jekyllrb.com/docs/collections/
# collections:
#   contents:
#         output: true
#         permalink:  /:collection/:path
#         author: host

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# page_generator

page_gen-dirs: false

page_gen:
  # Info page
  - data: 'eBook'
    template: 'page_gen/eBook'
    name: 'bookid'
    dir: 'preview'

  - data: 'distBook'
    template: 'page_gen/distBook'
    name: 'bookid'
    dir: 'preview'

  - data: 'paperBook'
    template: 'page_gen/paperBook'
    name: 'bookid'
    dir: 'preview'

  # Download page
  - data: 'eBook'
    template: 'page_gen/download'
    name: 'bookid'
    dir: 'download'

  - data: 'distBook'
    template: 'page_gen/download'
    name: 'bookid'
    dir: 'download'

  # - data: 'paperBook'
  #   template: 'page_gen/download'
  #   name: 'bookid'
  #   dir: 'download'
