name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v4
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: ${{ runner.os }}-gems-
        
    - name: Jekyll Actions
      # You may pin to the exact commit or the version.
      # uses: helaili/jekyll-action@8db04b1668404aa98f95c50219831db72ea34cfa
      uses: helaili/jekyll-action@2.3.1
      with:
        # The GITHUB_TOKEN secret
        token: ${{ secrets.GITHUB_TOKEN }}
        # The target branch name the site gets pushed to
        target_branch: gh-pages
        # pre_build_commands: # optional
